tag_new_version: echo error to stderr

diff --git a/contrib/sica/tag_new_version b/contrib/sica/tag_new_version
--- a/contrib/sica/tag_new_version
+++ b/contrib/sica/tag_new_version
@@ -15,7 +15,7 @@ EOF
 
 if test -z "$build"
 then 
-  echo "Invalid version tag: [$last_tag]"
+  echo "Invalid version tag: [$last_tag]" >&2
   exit 1 
 fi
 
